version: '3'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: frontend
        ports:
               - "80:80"
        volumes:
                  - /var/application/nginx/log:/var/log/nginx
                  - /var/application/nginx/cache:/var/cache/nginx
                  - /var/application/nginx/run:/var/run
        restart: always
        networks:
            - dd_network

networks:
  dd_network:
    name: dd_network
    driver: bridge
