version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"   # Map container port to host
    restart: always
    networks:
      - dd_network

networks:
  dd_network:
    name: dd_network
    driver: bridge
